import "../../styles/global.css";

import { Header, Link } from "../../components/Header";
import { Carousel } from "../../components/Carousel";
import { Footer } from "../../components/Footer";
import { Heading } from "../../components/Heading";
import { Label } from "../../components/Label";
import { Text } from "../../components/Text";

const hrefs: Link[] = [
    {
        href: "/",
        title: "Home"
    },
    {
        href: "/curriculo/#formacao",
        title: "Formação"
    },
    {
        href: "/curriculo/#stack",
        title: "Stack"
    },
    {
        href: "/curriculo/#certificados",
        title: "Certificados"
    }
];

export function Curriculo() {
    return (
        <div
            className="
                fixed
                top-0
                w-screen
                h-screen
                text-white
                overflow-auto
                scroll-smooth
                snap-mandatory
                snap-y
            "
        >
            <Header hrefs={hrefs}/>
            <div
                id="formacao"
                className="
                    gradient-sky
                    card
                "
            >
                <Heading
                    className="
                        animate-found
                    "
                >
                    Formação
                </Heading>
                <div
                    className="
                        w-[80vw]
                        gradient-black
                        p-4
                        rounded-lg
                    "
                >
                    <Heading>Universidade Federal do Ceará - Campus de Quixadá</Heading>
                    <Label>Ciência da Computação</Label>
                    <Text>Mar/2019 até o momento (3 anos e 11 meses)</Text>
                </div>
            </div>
            <div
                id="stack"
                className="
                    gradient-black
                    card
                "
            >
                <Heading>Stack</Heading>
                <div
                    className="
                        flex
                        gap-4
                        flex-wrap
                        justify-center
                    "
                >
                    <figure
                        className="
                            figure-secondary
                        "
                    >
                        <div>
                            <img 
                                src="/assets/profile/stack/Figma.svg"
                                alt="" 
                                className="
                                    z-[2]
                                    p-2
                                "
                            />
                            <img 
                                src="/assets/profile/stack/Figma.svg"
                                alt="" 
                                className="
                                absolute
                                top-2
                                p-2
                                blur-[8px]
                                z-[1]
                                animate-pulse
                                "
                            />
                        </div>
                        <figcaption>
                            <Label size="sm">Figma</Label>
                        </figcaption>
                    </figure>
                    <figure
                        className="
                            figure-secondary
                        "
                    >
                        <div>
                            <img 
                                src="/assets/profile/stack/HTML5.svg"
                                alt="" 
                                className="
                                    z-[2]
                                "
                            />
                            <img 
                                src="/assets/profile/stack/HTML5.svg"
                                alt="" 
                                className="
                                absolute
                                top-2
                                blur-[8px]
                                z-[1]
                                animate-pulse
                                "
                            />
                        </div>
                        <figcaption>
                            <Label size="sm">HTML</Label>
                        </figcaption>
                    </figure>
                    <figure
                        className="
                            figure-secondary
                        "
                    >
                        <div>
                            <img 
                                src="/assets/profile/stack/CSS3.svg"
                                alt="" 
                                className="
                                    z-[2]
                                "
                            />
                            <img 
                                src="/assets/profile/stack/CSS3.svg"
                                alt="" 
                                className="
                                absolute
                                top-2
                                blur-[8px]
                                z-[1]
                                animate-pulse
                                "
                            />
                        </div>
                        <figcaption>
                            <Label size="sm">CSS</Label>
                        </figcaption>
                    </figure>
                    <figure
                        className="
                            figure-secondary
                        "
                    >
                        <div>
                            <img 
                                src="/assets/profile/stack/Express.svg"
                                alt="" 
                                className="
                                    z-[2]
                                "
                            />
                            <img 
                                src="/assets/profile/stack/Express.svg"
                                alt="" 
                                className="
                                absolute
                                top-2
                                blur-[8px]
                                z-[1]
                                animate-pulse
                                "
                            />
                        </div>
                        <figcaption>
                            <Label size="sm">Express</Label>
                        </figcaption>
                    </figure>
                    <figure
                        className="
                            figure-secondary
                        "
                    >
                        <div>
                            <img 
                                src="/assets/profile/stack/Tailwindcss.svg"
                                alt="" 
                                className="
                                    z-[2]
                                "
                            />
                            <img 
                                src="/assets/profile/stack/Tailwindcss.svg"
                                alt="" 
                                className="
                                absolute
                                top-2
                                blur-[8px]
                                z-[1]
                                animate-pulse
                                "
                            />
                        </div>
                        <figcaption>
                            <Label size="sm">Tailwindcss</Label>
                        </figcaption>
                    </figure>
                    <figure
                        className="
                            figure-secondary
                        "
                    >
                        <div>
                            <img 
                                src="/assets/profile/stack/React.svg"
                                alt="" 
                                className="
                                    z-[2]
                                "
                            />
                            <img 
                                src="/assets/profile/stack/React.svg"
                                alt="" 
                                className="
                                absolute
                                top-2
                                blur-[8px]
                                z-[1]
                                animate-pulse
                                "
                            />
                        </div>
                        <figcaption>
                            <Label size="sm">React</Label>
                        </figcaption>
                    </figure>
                    <figure
                        className="
                            figure-secondary
                        "
                    >
                        <div>
                            <img 
                                src="/assets/profile/stack/Python.svg"
                                alt="" 
                                className="
                                    z-[2]
                                "
                            />
                            <img 
                                src="/assets/profile/stack/Python.svg"
                                alt="" 
                                className="
                                absolute
                                top-2
                                blur-[8px]
                                z-[1]
                                animate-pulse
                                "
                            />
                        </div>
                        <figcaption>
                            <Label size="sm">Python</Label>
                        </figcaption>
                    </figure>
                    <figure
                        className="
                            figure-secondary
                        "
                    >
                        <div>
                            <img 
                                src="/assets/profile/stack/TypeScript.svg"
                                alt="" 
                                className="
                                    z-[2]
                                "
                            />
                            <img 
                                src="/assets/profile/stack/TypeScript.svg"
                                alt="" 
                                className="
                                absolute
                                top-2
                                blur-[8px]
                                z-[1]
                                animate-pulse
                                "
                            />
                        </div>
                        <figcaption>
                            <Label size="sm">TypeScript</Label>
                        </figcaption>
                    </figure>
                    <figure
                        className="
                            figure-secondary
                        "
                    >
                        <div>
                            <img 
                                src="/assets/profile/stack/Node.svg"
                                alt="" 
                                className="
                                    z-[2]
                                "
                            />
                            <img 
                                src="/assets/profile/stack/Node.svg"
                                alt="" 
                                className="
                                absolute
                                top-2
                                blur-[8px]
                                z-[1]
                                animate-pulse
                                "
                            />
                        </div>
                        <figcaption>
                            <Label size="sm">Node</Label>
                        </figcaption>
                    </figure>
                    <figure
                        className="
                            figure-secondary
                        "
                    >
                        <div>
                            <img 
                                src="/assets/profile/stack/Git.svg"
                                alt="" 
                                className="
                                    z-[2]
                                "
                            />
                            <img 
                                src="/assets/profile/stack/Git.svg"
                                alt="" 
                                className="
                                absolute
                                top-2
                                blur-[8px]
                                z-[1]
                                animate-pulse
                                "
                            />
                        </div>
                        <figcaption>
                            <Label size="sm">Git</Label>
                        </figcaption>
                    </figure>
                </div>
            </div>
            <div
                id="certificados"
                className="
                    gradient-purple
                    card
                "
            >
                <Heading>Certificados</Heading>
                <Carousel
                    orientation="horizontal"
                    className="w-[90vw]"
                >
                    <div
                        className="
                            flex
                            justify-center
                            carousel-item
                            w-full
                        "
                    >
                        <figure
                            className="
                                figure-terciary
                            "
                        >
                            <img 
                                src="/assets/profile/certificates/html-basico-fundacao-bradesco.png" 
                                alt="" 
                                className="
                                    w-full
                                    h-[256px]
                                "
                            />
                            <figcaption
                                className="
                                    flex
                                    flex-col
                                    w-full
                                    h-full
                                    px-8
                                "
                            >
                                <Label size="lg">Instituição: Fundação Bradesco</Label>
                                <Text>Curso: HTML Básico</Text>
                                <a 
                                    href="/assets/profile/certificates/html-basico-fundacao-bradesco.png"
                                    target="_blanck"
                                    className="
                                        ml-auto
                                        mt-auto
                                        p-2
                                        rounded-full
                                        transition
                                        bg-cyan-600
                                        hover:bg-cyan-500
                                    "
                                >
                                    <Label>visualizar</Label>
                                </a>
                            </figcaption>
                        </figure>
                    </div>
                    <div
                        className="
                            flex
                            justify-center
                            carousel-item
                            w-full
                        "
                    >
                        <figure
                            className="
                                figure-terciary
                            "
                        >
                            <img 
                                src="/assets/profile/certificates/html-avancado-fundacao-bradesco.png" 
                                alt="" 
                                className="
                                    w-full
                                    h-[256px]
                                "
                            />
                            <figcaption
                                className="
                                    flex
                                    flex-col
                                    w-full
                                    h-full
                                    px-8
                                    gap-1
                                "
                            >
                                <Label size="lg">Instituição: Fundação Bradesco</Label>
                                <Text>Curso: HTML Avançado</Text>
                                <a 
                                    href="/assets/profile/certificates/html-avancado-fundacao-bradesco.png"
                                    target="_blanck"
                                    className="
                                        ml-auto
                                        mt-auto
                                        p-2
                                        rounded-full
                                        transition
                                        bg-cyan-600
                                        hover:bg-cyan-500
                                    "
                                >
                                    <Label>visualizar</Label>
                                </a>
                            </figcaption>
                        </figure>
                    </div>
                    <div
                        className="
                            flex
                            justify-center
                            carousel-item
                            w-full
                        "
                    >
                        <figure
                            className="
                                figure-terciary
                            "
                        >
                            <img 
                                src="/assets/profile/certificates/inovando-com-css-fundacao-bradesco.png" 
                                alt="" 
                                className="
                                    w-full
                                    h-[256px]
                                "
                            />
                            <figcaption
                                className="
                                    flex
                                    flex-col
                                    w-full
                                    h-full
                                    px-8
                                    gap-1
                                "
                            >
                                <Label size="lg">Instituição: Fundação Bradesco</Label>
                                <Text>Curso: Inovando com CSS</Text>
                                <a 
                                    href="/assets/profile/certificates/inovando-com-css-fundacao-bradesco.png"
                                    target="_blanck"
                                    className="
                                        ml-auto
                                        mt-auto
                                        p-2
                                        rounded-full
                                        transition
                                        bg-cyan-600
                                        hover:bg-cyan-500
                                    "
                                >
                                    <Label>visualizar</Label>
                                </a>
                            </figcaption>
                        </figure>
                    </div>
                    <div
                        className="
                            flex
                            justify-center
                            carousel-item
                            w-full
                        "
                    >
                        <figure
                            className="
                                figure-terciary
                            "
                        >
                            <img 
                                src="/assets/profile/certificates/html-e-css-na-pratica-fundacao-bradesco.png" 
                                alt="" 
                                className="
                                    w-full
                                    h-[256px]
                                "
                            />
                            <figcaption
                                className="
                                    flex
                                    flex-col
                                    w-full
                                    h-full
                                    px-8
                                    gap-1
                                "
                            >
                                <Label size="lg">Instituição: Fundação Bradesco</Label>
                                <Text>Curso: HTML e CSS na Prática</Text>
                                <a 
                                    href="/assets/profile/certificates/html-e-css-na-pratica-fundacao-bradesco.png"
                                    target="_blanck"
                                    className="
                                        ml-auto
                                        mt-auto
                                        p-2
                                        rounded-full
                                        transition
                                        bg-cyan-600
                                        hover:bg-cyan-500
                                    "
                                >
                                    <Label>visualizar</Label>
                                </a>
                            </figcaption>
                        </figure>
                    </div>
                    <div
                        className="
                            flex
                            justify-center
                            carousel-item
                            w-full
                        "
                    >
                        <figure
                            className="
                                figure-terciary
                            "
                        >
                            <img 
                                src="/assets/profile/certificates/introducao-ao-javascript-fundacao-bradesco.png" 
                                alt="" 
                                className="
                                    w-full
                                    h-[256px]
                                "
                            />
                            <figcaption
                                className="
                                    flex
                                    flex-col
                                    w-full
                                    h-full
                                    px-8
                                    gap-1
                                "
                            >
                                <Label size="lg">Instituição: Fundação Bradesco</Label>
                                <Text>Curso: Introdução ao JavaScript</Text>
                                <a 
                                    href="/assets/profile/certificates/introducao-ao-javascript-fundacao-bradesco.png"
                                    target="_blanck"
                                    className="
                                        ml-auto
                                        mt-auto
                                        p-2
                                        rounded-full
                                        transition
                                        bg-cyan-600
                                        hover:bg-cyan-500
                                    "
                                >
                                    <Label>visualizar</Label>
                                </a>
                            </figcaption>
                        </figure>
                    </div>
                    <div
                        className="
                            flex
                            justify-center
                            carousel-item
                            w-full
                        "
                    >
                        <figure
                            className="
                                figure-terciary
                            "
                        >
                            <img 
                                src="/assets/profile/certificates/introducao-ao-javascript-fundacao-bradesco.png" 
                                alt="" 
                                className="
                                    w-full
                                    h-[256px]
                                "
                            />
                            <figcaption
                                className="
                                    flex
                                    flex-col
                                    w-full
                                    h-full
                                    px-8
                                    gap-1
                                "
                            >
                                <Label size="lg">Instituição: Fundação Bradesco</Label>
                                <Text>Curso: Introdução ao JavaScript</Text>
                                <a 
                                    href="/assets/profile/certificates/introducao-ao-javascript-fundacao-bradesco.png"
                                    target="_blanck"
                                    className="
                                        ml-auto
                                        mt-auto
                                        p-2
                                        rounded-full
                                        transition
                                        bg-cyan-600
                                        hover:bg-cyan-500
                                    "
                                >
                                    <Label>visualizar</Label>
                                </a>
                            </figcaption>
                        </figure>
                    </div>
                    <div
                        className="
                            flex
                            justify-center
                            carousel-item
                            w-full
                        "
                    >
                        <figure
                            className="
                                figure-terciary
                            "
                        >
                            <img 
                                src="/assets/profile/certificates/crie-um-site-simples-fundacao-bradesco.png" 
                                alt="" 
                                className="
                                    w-full
                                    h-[256px]
                                "
                            />
                            <figcaption
                                className="
                                    flex
                                    flex-col
                                    w-full
                                    h-full
                                    px-8
                                    gap-1
                                "
                            >
                                <Label size="lg">Instituição: Fundação Bradesco</Label>
                                <Text>Curso: Crie um Site Simples com HTML, CSS e JavaScript</Text>
                                <a 
                                    href="/assets/profile/certificates/crie-um-site-simples-fundacao-bradesco.png"
                                    target="_blanck"
                                    className="
                                        ml-auto
                                        mt-auto
                                        p-2
                                        rounded-full
                                        transition
                                        bg-cyan-600
                                        hover:bg-cyan-500
                                    "
                                >
                                    <Label>visualizar</Label>
                                </a>
                            </figcaption>
                        </figure>
                    </div>
                    <div
                        className="
                            flex
                            justify-center
                            carousel-item
                            w-full
                        "
                    >
                        <figure
                            className="
                                figure-terciary
                            "
                        >
                            <img 
                                src="/assets/profile/certificates/trilha-conectar-do-discover-rocketseat.png" 
                                alt="" 
                                className="
                                    w-full
                                    h-[256px]
                                "
                            />
                            <figcaption
                                className="
                                    flex
                                    flex-col
                                    w-full
                                    h-full
                                    px-8
                                    gap-1
                                "
                            >
                                <Label size="lg">Instituição: Rocketseat</Label>
                                <Text>Curso: Conectar</Text>
                                <a 
                                    href="/assets/profile/certificates/trilha-conectar-do-discover-rocketseat.png"
                                    target="_blanck"
                                    className="
                                        ml-auto
                                        mt-auto
                                        p-2
                                        rounded-full
                                        transition
                                        bg-cyan-600
                                        hover:bg-cyan-500
                                    "
                                >
                                    <Label>visualizar</Label>
                                </a>
                            </figcaption>
                        </figure>
                    </div>
                    <div
                        className="
                            flex
                            justify-center
                            carousel-item
                            w-full
                        "
                    >
                        <figure
                            className="
                                figure-terciary
                            "
                        >
                            <img 
                                src="/assets/profile/certificates/trilha-fundamentar-do-discover-rocketseat.png" 
                                alt="" 
                                className="
                                    w-full
                                    h-[256px]
                                "
                            />
                            <figcaption
                                className="
                                    flex
                                    flex-col
                                    w-full
                                    h-full
                                    px-8
                                    gap-1
                                "
                            >
                                <Label size="lg">Instituição: Rocketseat</Label>
                                <Text>Curso: Fundamentar</Text>
                                <a 
                                    href="/assets/profile/certificates/trilha-fundamentar-do-discover-rocketseat.png"
                                    target="_blanck"
                                    className="
                                        ml-auto
                                        mt-auto
                                        p-2
                                        rounded-full
                                        transition
                                        bg-cyan-600
                                        hover:bg-cyan-500
                                    "
                                >
                                    <Label>visualizar</Label>
                                </a>
                            </figcaption>
                        </figure>
                    </div>
                </Carousel>
            </div>
            <Footer 
                title="Currículo" 
                terms="Copyright (c) 2023 Carlos Eduardo de Moura Gomes" 
                message="Se você chegou até aqui obrigado pela atenção"
            />
        </div>
    );
}