import '../../styles/global.css'

import { Profile } from '../../profile/Profile';
import { MyProfile } from '../../profile/MyProfile';
import { sendMessage } from '../../functions/sendMessage';

import { Header } from '../../components/Header';
import { Banner } from '../../components/Banner';
import { Card } from '../../components/Card';
import { List } from '../../components/List';

import { TypeAnimation } from 'react-type-animation';
import { motion } from "framer-motion"
import { useState } from 'react';
import nextId from 'react-id-generator';

export function LandingPage() {
    const [profile, setProfile] = useState(MyProfile as Profile);

    return (
        <div 
      className="
          fixed 
          top-0 
          w-screen 
          h-screen 
          bg-gradient-to-r 
          from-indigo-600 
          via-violet-600 
          to-purple-600 
          overflow-auto 
          scroll-smooth 
          scrollbar-hide 
          select-none
      "
    >
      <Header/>
      <Banner
          id="home"
      >
        <div
            className="
                min-h-[96px]
                text-xl 
                font-semibold 
                flex 
                flex-col 
                items-center
            "
        >
          <span>
            Eu sou&nbsp;
          </span>
          <TypeAnimation
            sequence={[
              "Desenvolvedor Front End",
              2000,
              "Universitário",
              2000
            ]}
            speed={50}
          wrapper="span"
            repeat={Infinity}
            className='text-purple-500 uppercase'
          />
        </div>
        <div
            className="
                flex
                justify-center
                min-w-[250px]
                min-h-[250px]
                relative
            "
        >
            <img 
                src={profile.imageUrl} 
                alt="" 
                className="
                    z-[3] 
                    absolute 
                    bottom-0
                "
            />
            <img 
                src="/Portfolio/assets/profile/banner/Blob.svg" 
                alt="" 
                className="
                    z-[2] 
                    absolute 
                    top-0
                "
            />
            <img 
                src="/Portfolio/assets/profile/banner/Blob.svg" 
                alt="" 
                className="
                    z-[1] 
                    absolute 
                    top-0 
                    blur-sm
                "
            />
        </div>
        <figcaption
            className="
                text-md
                w-[80vw]
                text-center
            "
        >
          {
            profile.bio.map((item) => (
              <p
                  key={nextId()}
              >
                { item }
              </p>
            ))
          }
        </figcaption>
        <div
             className="
                 flex
                 gap-2
                 p-2
             "
          >
            {
              profile.contacts.map((item) => (
                  <a 
                      key={nextId()}
                      href={ item.siteUrl }
                      target="_blank"
                      className="
                           rounded-md
                           hover:bg-violet-500
                           bg-gradient-to-b
                         from-neutral-300/30
                         via-neutral-600/60
                         to-neutral-800/80
                      "
                  >
                    <img src={ item.imageUrl } alt="" />
                  </a>
              ))
            }
          </div>
      </Banner>
      <Card
          id="projetos"
      >
        <h1
            className="
                text-xl 
                font-semibold 
                text-white
            "
        >
          Projetos
        </h1>
        <List>
          {
            profile.projects.map((item) => (
              <figure
                  key={nextId()}
                  className="
                      relative
                      flex
                      w-[50vw]
                      max-md:w-[80vw]
                      flex-col
                      items-center
                      justify-center
                      text-center
                      gap-4
                      p-4
                      rounded-lg
                      text-white
                      bg-gradient-to-b
                    from-neutral-300/30
                    via-neutral-600/60 
                    to-neutral-800/80
                    z-[1]
                  "
              >
                <motion.div
                    animate={{height: ["50%", "100%", "50%"]}}
                    transition={{duration: 10, repeat: Infinity}}
                    className="
                        rounded-lg
                        w-full
                        absolute
                        bottom-0
                        z-[-1]
                        bg-gradient-to-t
                        from-red-500
                        via-yellow-500
                        to-yellow-300
                    "
                ></motion.div>
                <h1
                    className="
                        text-xl
                        font-semibold
                    "
                >{ item.label }</h1>
                <img 
                    src={item.imageUrl} 
                    alt="" 
                    className="
                        rounded-lg
                        w-full
                    "
                />
                <figcaption
                    className="
                        flex
                        flex-col
                        gap-2
                        w-full
                    "
                >
                  <h1
                      className="
                          text-lg
                          font-semibold
                      "
                  >{item.description}</h1>
                  <div
                      className="
                          flex
                          items-center
                          justify-center
                          gap-4
                      "
                  >
                    <a 
                        href={ item.githubProjectUrl }
                        target="_blank"
                        className="
                            flex
                            items-center
                            justify-center
                            rounded-md
                            h-[32px]
                            flex-1
                            bg-violet-600
                            hover:bg-violet-500
                        "
                    >
                      GitHub
                    </a>
                    <a 
                        href={ item.siteProjectUrl }
                        target="_blank"
                        className="
                            flex
                            items-center
                            justify-center
                            rounded-md
                            h-[32px]
                            flex-1
                            bg-cyan-600
                            hover:bg-cyan-500
                        "
                    >
                      Site
                    </a>
                  </div>
                </figcaption>
              </figure>
            ))
          }
        </List>
      </Card>
      <Card
          id="formacao"
      >
        <h1
            className="
                text-xl 
                font-semibold 
                text-white
            "
        >
          Formação
        </h1>
        <List>
          {
            profile.educational.map((item) => (
              <div
                  key={nextId()}
                  className="
                      break-words
                      text-white
                      rounded-md
                      p-2
                      w-full
                      ring-2
                      ring-white
                      hover:ring-cyan-500
                  "
              >
                <h1
                     className="
                         text-xl
                         font-semibold
                     "
                >
                  { item.institution }
                </h1>
                <h1
                    className="
                        text-base
                    "
                >
                  { item.course }
                </h1>
                <h1
                    className="
                        text-sm
                        font-light
                    "
                >
                  { item.period }
                </h1>
              </div>
            ))
          }
        </List>
      </Card>
      <Card
          id="stack"
          className="
              bg-neutral-900
              text-white
          "
      >
        <h1
            className="
                text-xl 
                font-semibold
            "
        >
          Stack
        </h1>
        <List>
          {
            profile.stack.map((item) => (
              <figure
                  key={nextId()}
                  className="
                      relative
                      flex
                      flex-col
                      items-center
                      justify-center
                      gap-2
                      w-[80px]
                      h-[80px]
                  "
              >
                <img 
                    src={ item.imageUrl } 
                    alt="" 
                    className="
                        z-[2]
                    "
                />
                <img 
                    src={ item.imageUrl } 
                    alt="" 
                    className="
                       absolute
                       top-1
                       blur-sm
                       z-[1]
                       animate-pulse
                    "
                />
                <figcaption>
                  <h1>
                    { item.label }
                  </h1>
                </figcaption>
              </figure>
            ))
          }
        </List>
      </Card>
      <Card
          id="certificados"
          className="
            text-white
          "
      >
        <h1
            className="
                text-xl 
                font-semibold 
            "
        >
          Certificados
        </h1>
        <List>
          {
            profile.certificates.map((item) => (
              <figure
                  key={nextId()}
                  className="
                      w-[25vw]
                      max-md:w-[60vw]
                      flex
                      flex-col
                      justify-between
                      items-center
                      text-center
                      gap-4
                      pb-4
                      rounded-lg
                      bg-gradient-to-b
                    from-neutral-300/30
                    via-neutral-600/60 
                    to-neutral-800/80
                  "
              >
                <img 
                    src={ item.imageUrl } 
                    alt="" 
                    className="
                        w-full
                        rounded-lg
                    "
                />
                <figcaption
                    className="
                        w-full
                        flex
                        flex-col
                        gap-2
                        items-center
                    "
                >
                  <h1>{item.label}, da { item.institution }</h1>
                  <a 
                      href={ item.imageUrl }
                      target="_blank"
                      className="
                          ring-1
                          ring-white
                          w-[90%]
                          rounded-full
                          hover:text-cyan-500
                          hover:ring-cyan-500
                      "
                  >
                    Visualizar
                  </a>
                </figcaption>
              </figure>
            ))
          }
        </List>
      </Card>
      <Card
          id="habilidades"
          className="
              bg-neutral-900
              text-white
          "
      >
        <h1
            className="text-xl font-semibold text-white"
        >
          Habilidades
        </h1>
        <List>
          {
            profile.skills.map((item) => (
              <figure
                  key={nextId()}
                  className='
                      relative 
                      flex 
                      items-center 
                      justify-center 
                      w-[150px] 
                      h-[150px] 
                      rounded-full 
                      overflow-hidden
                      bg-gradient-to-b
                      from-neutral-300/30
                      via-neutral-600/60
                      to-neutral-800/80
                  '
              >
                <img 
                    src={ item.imageUrl } 
                    alt="" 
                    className='
                        absolute 
                        bottom-0
                        z-[1]
                    '
                />
                <img 
                    src={ item.imageUrl } 
                    alt="" 
                    className='
                        blur-sm
                        absolute 
                        bottom-0
                        z-[1]
                    '
                />
                <figcaption
                    className='
                        z-[2]
                        text-white
                        text-xl
                    '
                >
                  <h1>
                    { item.label }
                  </h1>
                </figcaption>
              </figure>
            ))
          }
        </List>
      </Card>
      <Card
          id="feedback"
          className="
              text-white
          "
      >
        <form 
            onSubmit={sendMessage}
            className="
                w-[80vw]
                px-8 
                py-4 
                rounded-md 
                flex 
                flex-col 
                items-center
                gap-4
                bg-gradient-to-b
              from-neutral-300/30
              via-neutral-600/60 
              to-neutral-800/80
            "    
        >
          <label htmlFor="textarea"
              className="
                  text-xl
              "
          >
              Feedback
          </label>
          <textarea 
              name="message" 
              id="textarea" 
              required 
              placeholder="Me envie seu feedback 😉"
              className="
                  w-full
                  p-2
                  bg-white/0 
                  resize-none 
                  ring-2 
                  ring-white
                  rounded-md
                  focus:outline-none
                  focus:ring-cyan-500
              "
          />
          <button
              type="submit"
              className="
                  bg-cyan-500
                  w-full
                  h-[32px]
                  rounded-full
                  hover:bg-cyan-300
              "
          >
            Enviar
          </button>
        </form>
      </Card>
      <Card
          className="
              relative
              bg-neutral-900
              text-white
              text-center
              justify-center
          "
      >
        <h1
            className="
                text-violet-500
                font-light
            "
        >
        Se você chegou até aqui obrigado pela atenção
        </h1>
        <h1
            className="
                text-2xl
                font-semibold
            "
        >
          { profile.portifolioName }
        </h1>
        <h1>
          { profile.portifolioLema }
        </h1>
      </Card>
    </div>
    );
}